import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { TaskEditorSheet } from "@/components/task-editor-sheet";
import { TaskRow } from "@/components/task-row";
import { useColors } from "@/hooks/use-colors";
import { dateKey, isSameDay } from "@/lib/date-utils";
import { useI18n } from "@/lib/i18n";
import type { Task } from "@/lib/tasks-context";
import { useTasks } from "@/lib/tasks-context";

const weekdaysByLanguage = { ru: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"], en: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], es: ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"], fr: ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"], de: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"], pt: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"], zh: ["一", "二", "三", "四", "五", "六", "日"], ar: ["الإث", "الث", "الأر", "الخ", "الجم", "السب", "الأح"], hi: ["सोम", "मंगल", "बुध", "गुरु", "शुक्र", "शनि", "रवि"], ja: ["月", "火", "水", "木", "金", "土", "日"] } as const;
const localeByLanguage = { ru: "ru-RU", en: "en-US", es: "es-ES", fr: "fr-FR", de: "de-DE", pt: "pt-BR", zh: "zh-CN", ar: "ar-SA", hi: "hi-IN", ja: "ja-JP" } as const;
function calendarDays(month: Date, firstDayOfWeek: 0 | 1) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = (first.getDay() - firstDayOfWeek + 7) % 7; const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return Array.from({ length: 42 }, (_, index) => index - start + 1).map((day) => day > 0 && day <= count ? new Date(month.getFullYear(), month.getMonth(), day) : undefined); }

export default function CalendarScreen() {
  const colors = useColors(); const { language, t } = useI18n(); const { tasks, settings, getList, getFolder, getTag, toggleTask } = useTasks();
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selected, setSelected] = useState(new Date()); const [editorOpen, setEditorOpen] = useState(false); const [editingTask, setEditingTask] = useState<Task | undefined>();
  const days = useMemo(() => calendarDays(month, settings.firstDayOfWeek), [month, settings.firstDayOfWeek]);
  const dueKeys = useMemo(() => new Set(tasks.filter((task) => task.dueAt && !task.completedAt).map((task) => dateKey(task.dueAt!))), [tasks]);
  const dayTasks = useMemo(() => tasks.filter((task) => task.dueAt && isSameDay(task.dueAt, selected)), [selected, tasks]);
  const moveMonth = (amount: number) => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + amount, 1));
  const label = new Intl.DateTimeFormat(localeByLanguage[language], { month: "long", year: "numeric" }).format(month);
  return <ScreenContainer><FlatList data={dayTasks} keyExtractor={(item) => item.id} contentContainerStyle={styles.content}
    ListHeaderComponent={<><View style={styles.header}><View><Text style={[styles.title, { color: colors.foreground }]}>{t("Календарь")}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{t("Планируйте важное по датам")}</Text></View><Pressable onPress={() => { setEditingTask(undefined); setEditorOpen(true); }} style={({ pressed }) => [styles.add, { backgroundColor: colors.primary }, pressed && styles.pressed]}><MaterialIcons name="add" size={23} color="#FFFFFF" /></Pressable></View>
      <View style={[styles.calendarCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.monthHeader}><Pressable onPress={() => moveMonth(-1)} style={styles.nav}><MaterialIcons name="chevron-left" size={25} color={colors.foreground} /></Pressable><Text style={[styles.monthTitle, { color: colors.foreground }]}>{label.charAt(0).toUpperCase() + label.slice(1)}</Text><Pressable onPress={() => moveMonth(1)} style={styles.nav}><MaterialIcons name="chevron-right" size={25} color={colors.foreground} /></Pressable></View><View style={styles.weekGrid}>{(settings.firstDayOfWeek === 0 ? [weekdaysByLanguage[language][6], ...weekdaysByLanguage[language].slice(0, 6)] : weekdaysByLanguage[language]).map((day) => <Text key={day} style={[styles.weekday, { color: colors.muted }]}>{day}</Text>)}</View><View style={styles.daysGrid}>{days.map((date, index) => { const selectedDay = date && isSameDay(date, selected); const today = date && isSameDay(date, new Date()); const hasTasks = date && dueKeys.has(dateKey(date)); return <Pressable disabled={!date} key={`${index}-${date?.toISOString() ?? "empty"}`} onPress={() => date && setSelected(date)} style={[styles.day, selectedDay && { backgroundColor: colors.primary }]}>{date ? <><Text style={[styles.dayText, { color: selectedDay ? "#FFFFFF" : colors.foreground }, today && !selectedDay && { color: colors.primary, fontWeight: "800" }]}>{date.getDate()}</Text>{hasTasks ? <View style={[styles.marker, { backgroundColor: selectedDay ? "#FFFFFF" : colors.primary }]} /> : <View style={styles.markerSpace} />}</> : null}</Pressable>; })}</View></View>
      <Text style={[styles.selectedTitle, { color: colors.foreground }]}>{new Intl.DateTimeFormat(localeByLanguage[language], { day: "numeric", month: "long" }).format(selected)}</Text></>}
    ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialIcons name="event-available" size={28} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>{t("В этот день свободно")}</Text><Text style={[styles.emptyText, { color: colors.muted }]}>{t("Выберите «+», чтобы запланировать дело.")}</Text></View>}
    renderItem={({ item }) => <TaskRow task={item} list={getList(item.listId)} folder={getFolder(item.folderId)} tags={item.tagIds.map((id) => getTag(id)).filter((tag): tag is NonNullable<typeof tag> => Boolean(tag))} onToggle={() => toggleTask(item.id)} onPress={() => { setEditingTask(item); setEditorOpen(true); }} />} ItemSeparatorComponent={() => <View style={{ height: 9 }} />} />
    <TaskEditorSheet visible={editorOpen} task={editingTask} onClose={() => setEditorOpen(false)} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }, title: { fontSize: 30, fontWeight: "800", letterSpacing: -0.6 }, subtitle: { marginTop: 4, fontSize: 15 }, add: { height: 44, width: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, pressed: { opacity: 0.72 }, calendarCard: { borderWidth: StyleSheet.hairlineWidth, padding: 15, borderRadius: 22 }, monthHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }, nav: { height: 36, width: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" }, monthTitle: { fontSize: 16, fontWeight: "700" }, weekGrid: { flexDirection: "row" }, weekday: { width: "14.285%", textAlign: "center", fontSize: 11, fontWeight: "700", paddingVertical: 4 }, daysGrid: { flexDirection: "row", flexWrap: "wrap" }, day: { width: "14.285%", height: 43, borderRadius: 12, alignItems: "center", justifyContent: "center", gap: 2 }, dayText: { fontSize: 14, lineHeight: 17, fontWeight: "600" }, marker: { width: 4, height: 4, borderRadius: 2 }, markerSpace: { height: 4 }, selectedTitle: { marginTop: 27, marginBottom: 12, fontSize: 20, fontWeight: "800" }, empty: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 18, padding: 24, alignItems: "center", gap: 7 }, emptyTitle: { marginTop: 5, fontSize: 16, fontWeight: "700" }, emptyText: { fontSize: 14 }, });
