import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { LanguagePickerSheet } from "@/components/language-picker-sheet";
import { useColors } from "@/hooks/use-colors";
import { getLanguage } from "@/lib/languages";
import { useI18n } from "@/lib/i18n";
import { pickBackup, shareBackup } from "@/lib/backup";
import type { ThemeMode } from "@/lib/tasks-context";
import { useTasks } from "@/lib/tasks-context";

const themes: { id: ThemeMode; label: string; icon: "brightness-auto" | "light-mode" | "dark-mode" }[] = [{ id: "system", label: "Как в системе", icon: "brightness-auto" }, { id: "light", label: "Светлая", icon: "light-mode" }, { id: "dark", label: "Тёмная", icon: "dark-mode" }];

export default function SettingsScreen() {
  const colors = useColors(); const { settings, updateSettings, setNotificationsEnabled, exportBackup, restoreBackup } = useTasks(); const { language, t } = useI18n(); const [languagePickerOpen, setLanguagePickerOpen] = useState(false); const selectedLanguage = getLanguage(settings.language); const forwardChevron = language === "ar" ? "chevron-left" : "chevron-right";
  const updateNotifications = async (value: boolean) => { const enabled = await setNotificationsEnabled(value); if (value && !enabled) Alert.alert(t("Разрешение не выдано"), t("Включите уведомления для FocusList в настройках устройства, чтобы получать напоминания.")); };
  const exportData = async () => { if (!(await shareBackup(exportBackup()))) Alert.alert(t("Резервная копия"), t("Экспорт недоступен на этом устройстве.")); };
  const importData = async () => { const backup = await pickBackup<ReturnType<typeof exportBackup>["state"]>(); if (!backup) return; Alert.alert(t("Импортировать резервную копию?"), t("Текущие данные будут заменены данными из файла."), [{ text: t("Отмена"), style: "cancel" }, { text: t("Импортировать"), style: "destructive", onPress: () => restoreBackup(backup) }]); };
  return <ScreenContainer><ScrollView contentContainerStyle={[styles.content, { paddingBottom: 112 }]} showsVerticalScrollIndicator={false}><Text style={[styles.title, { color: colors.foreground }]}>{t("settings")}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{t("settingsSubtitle")}</Text>
    <Text style={[styles.section, { color: colors.muted }]}>{t("appearance")}</Text><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{themes.map((theme, index) => <Pressable key={theme.id} onPress={() => updateSettings({ themeMode: theme.id })} style={({ pressed }) => [styles.row, index > 0 && { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth }, pressed && styles.pressed]}><View style={[styles.iconBox, { backgroundColor: settings.themeMode === theme.id ? `${colors.primary}18` : colors.background }]}><MaterialIcons name={theme.icon} size={20} color={settings.themeMode === theme.id ? colors.primary : colors.muted} /></View><Text style={[styles.rowText, { color: colors.foreground }]}>{t(theme.label)}</Text>{settings.themeMode === theme.id ? <MaterialIcons name="check" size={21} color={colors.primary} /> : null}</Pressable>)}</View>
    <Text style={[styles.section, { color: colors.muted }]}>{t("language").toUpperCase()}</Text><Pressable onPress={() => setLanguagePickerOpen(true)} style={({ pressed }) => [styles.card, styles.row, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><View style={[styles.iconBox, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name="language" size={20} color={colors.primary} /></View><View style={styles.rowCopy}><Text style={[styles.rowText, { color: colors.foreground }]}>{t("languageTitle")}</Text><Text style={[styles.rowSubtext, { color: colors.muted }]}>{`${selectedLanguage.flag} ${selectedLanguage.nativeLabel}`}</Text></View><MaterialIcons name={forwardChevron} size={21} color={colors.muted} /></Pressable>
    <Text style={[styles.section, { color: colors.muted }]}>{t("notifications").toUpperCase()}</Text><View style={[styles.card, styles.row, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.iconBox, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name="notifications-none" size={20} color={colors.primary} /></View><View style={styles.rowCopy}><Text style={[styles.rowText, { color: colors.foreground }]}>{t("notifications")}</Text><Text style={[styles.rowSubtext, { color: colors.muted }]}>{t("notificationsSub")}</Text></View><Switch value={settings.notificationsEnabled} onValueChange={(value) => void updateNotifications(value)} trackColor={{ false: colors.border, true: `${colors.primary}90` }} thumbColor={settings.notificationsEnabled ? colors.primary : "#FFFFFF"} /></View>
    <Text style={[styles.section, { color: colors.muted }]}>{t("РЕГИОН")}</Text><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.row}><View style={[styles.iconBox, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name="date-range" size={20} color={colors.primary} /></View><View style={styles.rowCopy}><Text style={[styles.rowText, { color: colors.foreground }]}>{t("Первый день недели")}</Text><View style={styles.weekChoices}>{([{ id: 1 as const, label: t("Понедельник") }, { id: 0 as const, label: t("Воскресенье") }]).map((option) => <Pressable key={option.id} onPress={() => updateSettings({ firstDayOfWeek: option.id })} style={({ pressed }) => [styles.weekChoice, { borderColor: settings.firstDayOfWeek === option.id ? colors.primary : colors.border, backgroundColor: settings.firstDayOfWeek === option.id ? `${colors.primary}18` : colors.background }, pressed && styles.pressed]}><Text style={[styles.weekChoiceText, { color: settings.firstDayOfWeek === option.id ? colors.primary : colors.muted }]}>{option.label}</Text></Pressable>)}</View></View></View></View>
    <Text style={[styles.section, { color: colors.muted }]}>{t("productivity")}</Text><Pressable onPress={() => router.push("/statistics" as never)} style={({ pressed }) => [styles.card, styles.row, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><View style={[styles.iconBox, { backgroundColor: `${colors.success}18` }]}><MaterialIcons name="insights" size={20} color={colors.success} /></View><View style={styles.rowCopy}><Text style={[styles.rowText, { color: colors.foreground }]}>{t("weeklyStats")}</Text><Text style={[styles.rowSubtext, { color: colors.muted }]}>{t("weeklyStatsSub")}</Text></View><MaterialIcons name={forwardChevron} size={21} color={colors.muted} /></Pressable>
    <Text style={[styles.section, { color: colors.muted }]}>{t("Резервная копия").toUpperCase()}</Text><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Pressable onPress={() => void exportData()} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={[styles.iconBox, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name="upload-file" size={20} color={colors.primary} /></View><View style={styles.rowCopy}><Text style={[styles.rowText, { color: colors.foreground }]}>{t("Экспортировать данные")}</Text><Text style={[styles.rowSubtext, { color: colors.muted }]}>{t("Включая язык и настройки")}</Text></View></Pressable><Pressable onPress={() => void importData()} style={({ pressed }) => [styles.row, { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }, pressed && styles.pressed]}><View style={[styles.iconBox, { backgroundColor: `${colors.warning}18` }]}><MaterialIcons name="download" size={20} color={colors.warning} /></View><View style={styles.rowCopy}><Text style={[styles.rowText, { color: colors.foreground }]}>{t("Импортировать данные")}</Text><Text style={[styles.rowSubtext, { color: colors.muted }]}>{t("Восстановить из файла резервной копии")}</Text></View></Pressable></View>
    <Text style={[styles.section, { color: colors.muted }]}>{t("about")}</Text><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.row}><View style={[styles.iconBox, { backgroundColor: `${colors.success}18` }]}><MaterialIcons name="check-circle-outline" size={20} color={colors.success} /></View><View><Text style={[styles.rowText, { color: colors.foreground }]}>FocusList</Text><Text style={[styles.rowSubtext, { color: colors.muted }]}>{t("brandSub")}</Text></View></View></View>
  <LanguagePickerSheet visible={languagePickerOpen} value={settings.language} onChange={(language) => updateSettings({ language })} onClose={() => setLanguagePickerOpen(false)} /></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20 }, title: { fontSize: 30, fontWeight: "800", letterSpacing: -0.6 }, subtitle: { marginTop: 4, fontSize: 15 }, section: { marginTop: 29, marginBottom: 9, fontSize: 11, fontWeight: "800", letterSpacing: 0.9 }, card: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 18, overflow: "hidden" }, row: { minHeight: 62, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 12 }, pressed: { opacity: 0.7 }, iconBox: { height: 36, width: 36, borderRadius: 12, alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1 }, rowText: { fontSize: 16, fontWeight: "700" }, rowSubtext: { marginTop: 3, fontSize: 12.5 }, weekChoices: { marginTop: 9, flexDirection: "row", flexWrap: "wrap", gap: 7 }, weekChoice: { minHeight: 30, paddingHorizontal: 10, borderRadius: 15, borderWidth: StyleSheet.hairlineWidth, justifyContent: "center" }, weekChoiceText: { fontSize: 12, fontWeight: "700" }, });
